name: hugeicons
description: "4,700+ Free Flutter Icons. Created by Hugeicons Pro Icon Library. Hugeicons Pro the most beautiful icon library for developers."
version: 1.0.2
homepage: https://hugeicons.com
repository: https://github.com/hugeicons/hugeicons-flutter
issue_tracker: https://github.com/hugeicons/hugeicons-flutter/issues
documentation: https://docs.hugeicons.com

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
